import { Motorcycle } from '../../domain/motorcycle/motorcycle.model';

// Datos de ejemplo mientras no hay backend. Se reemplazará por una
// llamada HTTP real en Ingeniería de Software 2 — cuando eso pase, solo
// cambia este archivo y el repositorio que lo usa, nada más.
export const MOCK_MOTORCYCLES: Motorcycle[] = [
  {
    id: 'yamaha-mt07',
    marca: 'Yamaha',
    modelo: 'MT-07',
    anio: 2024,
    categoria: 'Naked',
    cilindrada: 689,
    potencia: 73,
    torque: 67,
    precio: 27500000,
    imagen: '',
    descripcion: 'Naked de gama media, ágil y con buen torque a bajas revoluciones.',
  },
  {
    id: 'kawasaki-z650',
    marca: 'Kawasaki',
    modelo: 'Z650',
    anio: 2024,
    categoria: 'Naked',
    cilindrada: 649,
    potencia: 68,
    torque: 64,
    precio: 26800000,
    imagen: '',
    descripcion: 'Bicilíndrica equilibrada, pensada para uso diario y principiantes con experiencia.',
  },
  {
    id: 'honda-cb500f',
    marca: 'Honda',
    modelo: 'CB500F',
    anio: 2024,
    categoria: 'Naked',
    cilindrada: 471,
    potencia: 47,
    torque: 43,
    precio: 21900000,
    imagen: '',
    descripcion: 'Ideal para principiantes: liviana, económica de mantener y confiable.',
  },
  {
    id: 'bmw-g310gs',
    marca: 'BMW',
    modelo: 'G 310 GS',
    anio: 2024,
    categoria: 'Adventure',
    cilindrada: 313,
    potencia: 34,
    torque: 28,
    precio: 24500000,
    imagen: '',
    descripcion: 'Adventure liviana, buena para ciudad y primeras salidas fuera de asfalto.',
  },
  {
    id: 'ktm-390-adventure',
    marca: 'KTM',
    modelo: '390 Adventure',
    anio: 2024,
    categoria: 'Adventure',
    cilindrada: 373,
    potencia: 43,
    torque: 37,
    precio: 28900000,
    imagen: '',
    descripcion: 'Más potencia y equipamiento que su competencia directa, orientada a viajes.',
  },
  {
    id: 'suzuki-gixxer-sf250',
    marca: 'Suzuki',
    modelo: 'Gixxer SF250',
    anio: 2024,
    categoria: 'Deportiva',
    cilindrada: 249,
    potencia: 26,
    torque: 22,
    precio: 15900000,
    imagen: '',
    descripcion: 'Deportiva de entrada, económica y liviana para uso diario y ciudad.',
  },
  {
    id: 'ktm-duke-390-ng',
    marca: 'KTM',
    modelo: 'Duke 390 NG',
    anio: 2027,
    categoria: 'Naked',
    cilindrada: 373,
    potencia: 43,
    torque: 37,
    precio: 31000000,
    imagen: '',
    descripcion: 'Es ampliamente conocida por su apodo de "The Corner Rocket" debido a su peso ligero, chasis afilado y excelente entrega de potencia en curvas',
  },
];
